baseURL = "https://txt.netescape.org"
title = ".TXT"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
  
theme="the-roots-home"

#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"
[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"

[markup.highlight]
codeFences         = true
guessSyntax        = false
hl_Lines           = ""
lineNoStart        = 1
lineNos            = true
lineNumbersInTable = true
noClasses          = true
style              = "fruity"
tabWidth           = 4
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote       = true
linkify        = true
strikethrough  = true
table          = true
taskList       = true
typographer    = true
[markup.goldmark.parser]
attribute         = true
autoHeadingID     = true
autoHeadingIDType = "github"
[markup.goldmark.renderer]
hardWraps = false
unsafe    = true
xhtml     = false